// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbcxcbuvbvlsahcskiws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiY3hjYnV2YnZsc2FoY3NraXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTk2ODUsImV4cCI6MjA2NTQ5NTY4NX0.veJIWa_GEWNTjMLCJVU36AgyO4bV5KqT3sZUGziIE_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);